export const data = [
    {
        id:'dasda32',
        name: 'Harinder Singh',
        compnayName:'geo constructions inc',
        expertise: ['basement-renovation', 'concrete'],
        yearsOfExperience: 5,
        services: ['basement-renovation','painter','concrete','framing','kitchen-renovation'],
        imgURL:'https://assets-global.website-files.com/5e29591964852b5d27d96ea4/629dc3fb3c8c3e37c53ae814_Harinder%20Singh.jpg'
    },
    {
        name: 'Baghel Singh',
        compnayName:'Good Construction Inc',
        expertise: ['basement-renovation', 'concrete'],
        yearsOfExperience: 6,
        services: ['basement-renovation','concrete','framing','kitchen-renovation','washroom-renovation'],
        imgURL:'https://media.licdn.com/dms/image/C5603AQErwgCI51Hg3w/profile-displayphoto-shrink_800_800/0/1605752241012?e=2147483647&v=beta&t=FIw3Nk-G6fp74cnrgIuebRX6lvbFejmnPhdI7G24kbU',
        id:'dasda33',
    },
    {
        name: 'Amrinder Singh',
        compnayName:'Punjab Constructions Inc',
        expertise: ['basement-renovation', 'concrete'],
        yearsOfExperience: 7,
        services: ['basement-renovation','concrete','framing','kitchen-renovation'],
        imgURL:'https://english.cdn.zeenews.com/sites/default/files/styles/zm_700x400/public/2023/02/24/1158960-lovepreet-singh.jpg?im=Resize=(1280,720)',
        id:'dasda34',
    },
    {
        name: 'Jugraj Singh',
        compnayName:'singh constructions inc',
        expertise: ['basement-renovation', 'h-vac'],
        yearsOfExperience: 15,
        services: ['basement-renovation','H-vav','plumbing'],
        imgURL:'https://songs6.vlcmusic.com/tiny_image/timthumb.php?q=100&w=250&src=images/47064.png',
        id:'dasda35',
    },
    {
        name: 'Mushaqat Singh',
        compnayName:'Khalsa constructions inc',
        expertise: ['basement-renovation', 'framing'],
        yearsOfExperience: 5,
        services: ['basement-renovation','flooring','framing','kitchen-renovation'],
        imgURL:'https://media.licdn.com/dms/image/C5603AQGoGYvckPUwvg/profile-displayphoto-shrink_800_800/0/1612350292061?e=1700092800&v=beta&t=NmVQe_JRuV26hnzydnYZm6vMpq9nHBSGHdLvMI9_MV0',
        id:'dasda36',
    },
    {
        name: 'Sukhpal Singh',
        compnayName:'Panj constructions ltd',
        expertise: ['basement-renovation', 'kitchen-cabinet'],
        yearsOfExperience: 10,
        services: ['basement-renovation','framing','kitchen-kabinet'],
        imgURL:'https://i1.sndcdn.com/artworks-000103326303-e63itx-t500x500.jpg',
        id:'dasda37',
    },
    {
        name: 'Nishan Singh',
        compnayName:'Vaho builders inc',
        expertise: ['basement-renovation', 'concrete'],
        yearsOfExperience: 25,
        services: ['basement-renovation','painter','concrete','framing','kitchen-renovation'],
        imgURL:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQeL0D6WWsTiyeWdzckXX5Epd8X3NODb809bQ&usqp=CAU',
        id:'dasda38',
    },
    {
        name: 'Ranjeet Singh',
        compnayName:'Elite-5-Builders',
        expertise: ['basement-renovation', 'Landscaping'],
        yearsOfExperience: 5,
        services: ['basement-renovation','painter','Landscaping','washroom-remodel','kitchen-remodel'],
        imgURL:'https://media.licdn.com/dms/image/C4E03AQEmYLhJKZVYtw/profile-displayphoto-shrink_800_800/0/1630873184447?e=1700092800&v=beta&t=kZvC_kd4zfwBKhI3SFz6OI5XrNwSoCKshjxRfWQUq0I',
        id:'dasda39',
    },
    {
        id:'kolda32',
        name: 'Harinder Singh',
        compnayName:'geo constructions inc',
        expertise: ['basement-renovation', 'concrete'],
        yearsOfExperience: 5,
        services: ['basement-renovation','painter','concrete','framing','kitchen-renovation'],
        imgURL:'https://assets-global.website-files.com/5e29591964852b5d27d96ea4/629dc3fb3c8c3e37c53ae814_Harinder%20Singh.jpg'
    },
    {
        name: 'Baghel Singh',
        compnayName:'Good Construction Inc',
        expertise: ['basement-renovation', 'concrete'],
        yearsOfExperience: 6,
        services: ['basement-renovation','concrete','framing','kitchen-renovation','washroom-renovation'],
        imgURL:'https://media.licdn.com/dms/image/C5603AQErwgCI51Hg3w/profile-displayphoto-shrink_800_800/0/1605752241012?e=2147483647&v=beta&t=FIw3Nk-G6fp74cnrgIuebRX6lvbFejmnPhdI7G24kbU',
        id:'kolda33',
    },
    {
        name: 'Amrinder Singh',
        compnayName:'Punjab Constructions Inc',
        expertise: ['basement-renovation', 'concrete'],
        yearsOfExperience: 7,
        services: ['basement-renovation','concrete','framing','kitchen-renovation'],
        imgURL:'https://english.cdn.zeenews.com/sites/default/files/styles/zm_700x400/public/2023/02/24/1158960-lovepreet-singh.jpg?im=Resize=(1280,720)',
        id:'kolda34',
    },
    {
        name: 'Jugraj Singh',
        compnayName:'singh constructions inc',
        expertise: ['basement-renovation', 'h-vac'],
        yearsOfExperience: 15,
        services: ['basement-renovation','H-vav','plumbing'],
        imgURL:'https://songs6.vlcmusic.com/tiny_image/timthumb.php?q=100&w=250&src=images/47064.png',
        id:'kolda35',
    },
    {
        name: 'Mushaqat Singh',
        compnayName:'Khalsa constructions inc',
        expertise: ['basement-renovation', 'framing'],
        yearsOfExperience: 5,
        services: ['basement-renovation','flooring','framing','kitchen-renovation'],
        imgURL:'https://media.licdn.com/dms/image/C5603AQGoGYvckPUwvg/profile-displayphoto-shrink_800_800/0/1612350292061?e=1700092800&v=beta&t=NmVQe_JRuV26hnzydnYZm6vMpq9nHBSGHdLvMI9_MV0',
        id:'kolda36',
    },
    {
        name: 'Sukhpal Singh',
        compnayName:'Panj constructions ltd',
        expertise: ['basement-renovation', 'kitchen-cabinet'],
        yearsOfExperience: 10,
        services: ['basement-renovation','framing','kitchen-kabinet'],
        imgURL:'https://i1.sndcdn.com/artworks-000103326303-e63itx-t500x500.jpg',
        id:'kolda37',
    },
    {
        name: 'Nishan Singh',
        compnayName:'Vaho builders inc',
        expertise: ['basement-renovation', 'concrete'],
        yearsOfExperience: 25,
        services: ['basement-renovation','painter','concrete','framing','kitchen-renovation'],
        imgURL:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQeL0D6WWsTiyeWdzckXX5Epd8X3NODb809bQ&usqp=CAU',
        id:'kolda38',
    },
    {
        name: 'Ranjeet Singh',
        compnayName:'Elite-5-Builders',
        expertise: ['basement-renovation', 'Landscaping'],
        yearsOfExperience: 5,
        services: ['basement-renovation','painter','Landscaping','washroom-remodel','kitchen-remodel'],
        imgURL:'https://media.licdn.com/dms/image/C4E03AQEmYLhJKZVYtw/profile-displayphoto-shrink_800_800/0/1630873184447?e=1700092800&v=beta&t=kZvC_kd4zfwBKhI3SFz6OI5XrNwSoCKshjxRfWQUq0I',
        id:'kolda39',
    },
]